### ISSUE TITLE
Sandybay 17 won't load

### ISSUE THREAD

**Issue by pvajko** [pvajko/course-generator#1]
@gec100 i'm having trouble wit field 8 in Sandybay 17 map.

![8e7e2a60-fcf6-11e6-8354-0672bb528181](https://cloud.githubusercontent.com/assets/2379521/23362937/af07cb30-fcbd-11e6-8e53-716c835faaf7.JPG)
fileld is quite simple but coursegen would not load it to generate the course. After entering the number from the list and [enter], nothing happens. just like it waits for something else. if i than enter 0 it exits normally.

attached is the course from the CP_storage

https://github.com/Courseplay/courseplay/files/803718/courseStorage0002.txt

**Comment by pvajko** [comment]
Loads fine for me. Do you see any messages in the command line window where you started it? What if you start it without the game running?

**Comment by gec100** [comment]
no messages. I'll check starting without game in a sec.

**Comment by pvajko** [comment]
Also, can you send me the courseManager.xml file?

**Comment by pvajko** [comment]
Just last night I tried Field 11 there, harvesting, cultivating and sowing (with reverse course) and was fine. Weird.

**Comment by gec100** [comment]
now it loads fine. game is off.
[courseManager.txt](https://github.com/pvajko/course-generator/files/803787/courseManager.txt)

**Comment by gec100** [comment]
but i don't think i had that problem on the computer at home. right now i'm "working" ;)

i'm more "at work" than "working" :D

**Comment by pvajko** [comment]
Was this a course you just created in the game before trying to open
it? 

On 2017-02-27 07:43, gec100 wrote: 

> now it loads fine. game is
off.
> courseManager.txt [1]

 

Links:
------
[1]
https://github.com/pvajko/course-generator/files/803787/courseManager.txt

**Comment by gec100** [comment]
yes

**Comment by pvajko** [comment]
Just for the record, this was most likely a bug reported in #4
