### ISSUE TITLE
Can't load generated field edge

### ISSUE THREAD

**Issue by JDTiger** [pvajko/course-generator#11]
Hey,
when trying to generate a course from a saved fieldedge, i get the following error:
```
C:\Users\nitro\Desktop\FS17-CourseGen>lua53.exe startCourseGenerator.lua "c:\Users\nitro\Documents\My Games\FarmingSimulator2017\savegame20

Guettin_V2.SampleModMap

This is a savedir for map Guettin_V2.SampleModMap, will save generated course to c:\Users\nitro\Documents\My Games\FarmingSimulator2017\savegame20\..\CoursePlay_Courses\Guettin_V2.SampleModMap

Can't open c:\Users\nitro\Documents\My Games\FarmingSimulator2017\savegame20\..\CoursePlay_Courses\Guettin_V2.SampleModMap\courseManager.xml.
```

Greets JD_Tiger

**Comment by pvajko** [comment]
I think you add a backslash (\) it'll work (savegame20\ instead of 
savegame20). It's just a workaround, I'll fix it later.

**Comment by JDTiger** [comment]
nope, still get
`C:\Users\nitro\Desktop\FS17-CourseGen>lua53.exe startCourseGenerator.lua "c:\Users\nitro\Documents\My Games\FarmingSimulator2017\savegame20\
Guettin_V2.SampleModMap
This is a savedir for map Guettin_V2.SampleModMap, will save generated course to c:\Users\nitro\Documents\My Games\FarmingSimulator2017\savegame20\\..\CoursePlay_Courses\Guettin_V2.SampleModMap
Can't open c:\Users\nitro\Documents\My Games\FarmingSimulator2017\savegame20\\..\CoursePlay_Courses\Guettin_V2.SampleModMap\courseManager.xml.`

**Comment by pvajko** [comment]
Weird. What does

dir |c:\Users\nitro\Documents\My 
Games\FarmingSimulator2017\||CoursePlay_Courses|

|show?
|

||

**Comment by JDTiger** [comment]
```
C:\Users\nitro\Desktop\FS17-CourseGen>dir |c:\Users\nitro\Documents\My
'c:\Users\nitro\Documents\My' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\nitro\Desktop\FS17-CourseGen>Games\FarmingSimulator2017\||CoursePlay_Courses|
```

**Comment by pvajko** [comment]
I'm sorry, those email replies don't format well, what I meant is:

`dir "c:\Users\nitro\Documents\My Games\FarmingSimulator2017\CoursePlay_Courses"`

**Comment by JDTiger** [comment]
```
C:\Users\nitro\Desktop\FS17-CourseGen>dir c:\Users\nitro\Documents\My Games\FarmingSimulator2017\CoursePlay_Courses
The system cannot find the path specified.
```

But the folder is at the path specified...

**Comment by pvajko** [comment]
You had the " marks in there, right?

Is there a Guettin_V2.SampleModMap folder under CoursePlay_Courses? What is under CoursePlay_Courses?

We read  Guettin_V2.SampleModMap from savegame20\careerSavegame.xml and expect to find that folder under CoursePlay_Courses.

**Comment by JDTiger** [comment]
yes as seen above, i updated it after seeing you last edit...

**Comment by pvajko** [comment]
Is that possible that you have never saved a Courseplay course from that map?

**Comment by JDTiger** [comment]
yep... is that the problem?

**Comment by pvajko** [comment]
Yes, just save any course from that map and it'll be fine as it will create the folder under CoursePlay_Courses.

**Comment by JDTiger** [comment]
will do... suggestion: include a check, when folder does not exist; create folder
Or something along that lines...

**Comment by JDTiger** [comment]
ok, works now....

**Comment by pvajko** [comment]
Thanks.
I know it could create a new folder and all that, but this is meant to be a temporary solution until it gets integrated into Courseplay. I'd rather spend time on optimizing the track generation.
