### ISSUE TITLE
Calculating wierd fields

### ISSUE THREAD

**Issue by JDTiger** [pvajko/course-generator#12]
Hey,
I ran into some problems with fields of wierd forms.
As example, I'll take Field #1 from the map Güttin (https://www.modhoster.de/mods/guttin--2).

![Image of PDA](https://images.modhoster.de/system/files/0080/3108/huge/guttin--2.jpg)

the suggestion of course generator for this field is :
![Image of Course](http://i.imgur.com/K63nsfu.jpg)

**Comment by pvajko** [comment]
Yes, that's a weird one. My algorithm can't handle these it can't split a non convex field like this into multiple segments, that's a limitation I am aware of. It is far from trivial to generate a track for these, people publish papers in scientific journals about it.
This particular one should be split into four section, generate tracks for each of those and tracks for connecting the four sections. It is my long term target, but this won't be fixed overnight.

**Comment by JDTiger** [comment]
Hehe... while I do know its quite complicated, i didn't knew its that hard :D 
anyway, take your time on this, i just wanted to bring it up, but its no issue that is extremely urgent to me, just something, wich would be nice in the long run

**Comment by pvajko** [comment]
Two relevant papers for the record:

[An Optimized Field Coverage Planning Approach for Navigation of Agricultural Robots in Fields Involving Obstacle Areas](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwigvLTzheXSAhVj74MKHWWZCO8QFggfMAA&url=http%3A%2F%2Fcdn.intechopen.com%2Fpdfs%2F44525%2FInTech-An_optimized_field_coverage_planning_approach_for_navigation_of_agricultural_robots_in_fields_involving_obstacle_areas.pdf&usg=AFQjCNHf5GS7ALNXb5CM7wbc9duQeA2Ugg&sig2=cklaMlvyRRsr44HAp3M8pQ)

[Path Planning Algorithms for Agricultural Machines](https://ecommons.cornell.edu/handle/1813/10604)

**Comment by pvajko** [comment]
https://github.com/pvajko/course-generator/releases/tag/v0.6 can now handle these weird fields with limitations, see release notes and the readme.

**Comment by JDTiger** [comment]
Nice, will take a look in the next few days...

**Comment by pvajko** [comment]
Closing, no complaints so far.
