### ISSUE TITLE
Optimizing headland corners

### ISSUE THREAD

**Issue by pvajko** [pvajko/course-generator#13]
@Satissis you mentioned this in the Coursplay issue:

> Then if the degree from 1 waypoint to the next one is bigger that..... let's say 60 degree, it should make an turn start and turn end on that waypoint, so I can start incorporate some headland turn maneuvers, which should also help on those corners where it misses some areas. 

The question is, if I implement that if the direction change is over a threshold between two waypoints then I add turn start and turn end attributes to the generated course, would it work with the current Courseplay version?

**Comment by Satissis** [comment]
Nop it would not. It will do some kind of turn maneuver, but I don't think it would be pretty.

**Comment by pvajko** [comment]
True :) Just tried it... 
Anyway, I have a new headland generation algorithm in place, with smooth corners and 10% overlap there is just two tiny little spot of fruit skipped:

![field8](https://cloud.githubusercontent.com/assets/2379521/23837248/4fdf9502-0753-11e7-933b-ea4686d2a0e6.PNG)

**Comment by pvajko** [comment]
Just to record the progress here, we have so far the following options:
1. Overlap the headland tracks. Already implemented, just 10% overlap helps a lot, but obviously this is just a workaround, not a solution.
2. The master branch has the round corner feature implemented, which means that we generate the headland tracks from the inside out. If we do this, the innermost track corners will be a little square but as you progress outward they'll be rounder. This is a [rounded corner](https://cloud.githubusercontent.com/assets/2379521/25396371/fed7f77a-29a9-11e7-9abc-0662df59878c.PNG) generated from inside out, and [this](https://cloud.githubusercontent.com/assets/2379521/25396365/f3aa9a4c-29a9-11e7-98e8-023221750045.PNG) is a regular one, generated from the outside in. This leaves almost zero crop between the tracks but there's an area in the corner which is not worked. The size of this unworked area depends on the turning radius, the working width and number of headland tracks. 
3. 1 and 2 does not take into account the turning radius of the vehicle. I have an algorithm in the [radius branch](https://github.com/pvajko/course-generator/tree/radius) which can determine if a corner can round any corner with a given radius. Using this on the innermost headland track and then generating the headlands outwards guarantees no crop missed between the tracks but you still have the unworked area in the corner.
4. There is no way to cover 100% of the field without implementing some kind of half Y turn in sharp corners where the vehicle must back up. The existing algorithms can easily determine if a vehicle can make a turn without backing up and if not, it can mark the waypoints where the vehicle must make a half Y turn.
