### ISSUE TITLE
Can't start the generator: " stdin:1: syntax error near 'startCourseGenerator' "

### ISSUE THREAD

**Issue by Kattebakke** [pvajko/course-generator#14]
I am completely new to the course generator and after reading the readme I still can't figure out what I do wrong since I get that error. Am I missing a file? Have I mis-typed something that I oversee? It is probably a stupid mistake that make me facepalm, but Im completely lost at this moment. 

I have included this screenshot of both folders where the courses are located and where the generator is extracted to. 

![coursegenerator](https://cloud.githubusercontent.com/assets/24994460/24074132/00c98504-0c03-11e7-9be9-12b0e5d8eefa.png)

**Comment by pvajko** [comment]
Looks like you started lua53.exe from the Total Commander which started the lua interpreter in interactive mode. That's not how to do it.
You should open a plain command shell (cmd), change to the directory where you unzipped the course-generator and issue that command in the shell.

**Comment by Kattebakke** [comment]
Oh, I didnt get that. Can't find where it says that you need to start a cmd to get it to work. At #4 of the readme under usage it just says "type: lua.exe startcoursegenerator.lua ... etc..." 

But now I figured out that I have to use cmd, I still cant get it to work. I have tried a bunch of different  commands, but still no luck. 

1: I open CMD
2: By standard,, CMD opens with "C:\users\Rasmus>"
3a: I type what the readme says (with the location of the generator) and get what is marked in red
[OR]
3b; I navigate to where the generator is extracted and execute the lua53.exe-file, followed what the radme says and get what is marked in green.
![5](https://cloud.githubusercontent.com/assets/24994460/24074749/f71273fc-0c0e-11e7-844a-a9425b042a1a.png)

If I just ntry to navigate the CMD to the folder where the generator is located, CMD says: 'downloads\course-generator' (with or without a '\' at the end) was not recognized as an intern or extern command, program or batchfile
- I think is the correct translation to english


And I just want to be clear: I dont say that your script dont work, I say that I am too stupid to get it to work. And I hate that, because I absolutely love the good modders that make awesome scripts for the commynity..

**Comment by pvajko** [comment]
No problem @Kattebakke, looking at your screenshots what you have to do is this:
Open a CMD
Type these two commands, first:
`cd downloads\course-generator`
then
`lua53.exe startCourseGenerator.lua "C:\users\rasmus\Documents\My Games\FarmingSimulator2017\CoursePlay_Courses\FS17_GemeindeRade.GemeindeRade"`

**Comment by Kattebakke** [comment]
You are a saint! Thank you for spending time on helping a noob. I finally got it open and loaded a course. Now to mess around with it. Again, thank you very much
