### ISSUE TITLE
Tractor with sowing machine not turning

### ISSUE THREAD

**Issue by pvajko** [pvajko/course-generator#16]
Not sure if this is a problem with the generator or with CP, so opening it here first to seek for advice, I think @Satissis would be able to help.

The problem is that sometimes the tractor does not turn at the end of the lane, instead it drives straight forward until it hits something and starts slipping. I see the turn is generated (debug 14), seems to be fine but it disappears in a second and the tractor keeps driving in the original direction.

I have a log for the exact same turn, one good, where it successfully turned and a second one where it drove straight ahead:

Good turn:

> [dbg14 lp87691] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=57.65, posZ=-316.16, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) courseplay:getLaneInfo(), On Lane Nummber = 9, Number of Lanes = 27
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) wp783=-94.1°, wp782=135.1°, directionDifferentce = 41.0°
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) targetDeltaX=6.03, targetDeltaZ=-10.93
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn Data) frontMarker="-6.468994140625", halfVehicleWidth="2.5", directionNodeToTurnNodeLength="6.7241363525391", wpChangeDistance="3"
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn Data) reverseWPChangeDistance="5", direction="1", haveHeadlands="true", headlandHeight="15"
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn Data) numLanes="27", onLaneNum="9", turnOnField="true", reverseOffset="-5.7829284667969"
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn Data) haveWheeledImplement="true", reversingWorkTool="table: 0x01d0c1e18988", turnRadius="6.2206535339355", turnDiameter="12.441307067871"
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn Data) targetNode="92841", targetDeltaX="6.0264129638672", targetDeltaZ="-5.1519470214844", zOffset="-5.7829284667969"
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn Data) reverseOffset="-5.7829284667969", isHarvester="false"
##################################################
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) Using Questionmark Turn
##################################################
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) centerOffset=-0.19424057006836, sideB=6.0264129638672, sideC=12.441307067871, centerHeight=10.884322135346
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) canTurnOnHeadland=true, headlandHeight=15.00m, spaceNeeded=14.50m
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) doNormalTurn=true, haveHeadlands=true, 8.9m < 120.0m
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) centerHeightOffset=-5.7829284667969, reverseOffset=-5.7829284667969, zOffset=-5.7829284667969, turnRadius=6.2206535339355
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) startRot=44, endRot=-73, degreeStep=9, degreeToTurn=241, clockWice=1
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) numberOfWaypoints=27, newDegreeStep=8
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 1 curentRotation=44
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 2 curentRotation=53
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 3 curentRotation=62
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 4 curentRotation=71
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 5 curentRotation=80
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 6 curentRotation=89
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 7 curentRotation=98
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 8 curentRotation=107
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 9 curentRotation=116
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 10 curentRotation=125
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 11 curentRotation=134
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 12 curentRotation=143
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 13 curentRotation=152
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 14 curentRotation=161
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 15 curentRotation=169
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 16 curentRotation=178
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 17 curentRotation=187
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 18 curentRotation=196
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 19 curentRotation=205
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 20 curentRotation=214
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 21 curentRotation=223
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 22 curentRotation=232
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 23 curentRotation=241
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 24 curentRotation=250
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 25 curentRotation=259
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 26 curentRotation=268
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 27 curentRotation=277
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) startRot=106, endRot=44, degreeStep=-9, degreeToTurn=61, clockWice=-1
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) numberOfWaypoints=8, newDegreeStep=-8
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 1 curentRotation=106
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 2 curentRotation=97
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 3 curentRotation=88
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 4 curentRotation=79
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 5 curentRotation=71
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 6 curentRotation=62
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 7 curentRotation=53
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 8 curentRotation=44
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=35.24, posZ=-302.20, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=34.18, posZ=-301.14, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=33.12, posZ=-300.08, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=33.12, posZ=-300.08, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=33.12, posZ=-300.08, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=32.07, posZ=-299.03, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=31.03, posZ=-297.99, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=29.98, posZ=-296.94, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=28.93, posZ=-295.89, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=27.89, posZ=-294.85, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=26.84, posZ=-293.80, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=25.79, posZ=-292.75, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=24.75, posZ=-291.71, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=23.70, posZ=-290.66, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=22.65, posZ=-289.61, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=21.60, posZ=-288.56, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=20.56, posZ=-287.52, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=19.51, posZ=-286.47, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=18.46, posZ=-285.42, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=17.42, posZ=-284.38, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=16.37, posZ=-283.33, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=15.32, posZ=-282.28, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=15.32, posZ=-282.28, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=37.36, posZ=-304.32, turnEnd=true, turnReverse=true, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=38.11, posZ=-305.07, turnEnd=true, turnReverse=true, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=38.85, posZ=-305.81, turnEnd=true, turnReverse=true, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=38.85, posZ=-305.81, turnEnd=true, turnReverse=true, changeWhenPosible=false
[dbg14 lp88122] AgroStar 6.61 (#1):(Turn) Generated 62 Turn Waypoints
##################################################
[dbg14 lp88122] AgroStar 6.61 (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp88152] AgroStar 6.61 (#1): curStage=0, refSpeed=10.00, curSpeed=3.58 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp89011] AgroStar 6.61 (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp89061] AgroStar 6.61 (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp89101] AgroStar 6.61 (#1): curStage=0, refSpeed=20.00, curSpeed=7.04 -> resetCustomTimer(..., "slippingStage1")

Bad turn:

> [dbg14 lp68248] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=57.65, posZ=-316.16, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) courseplay:getLaneInfo(), On Lane Nummber = 9, Number of Lanes = 27
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) wp783=-94.1°, wp782=135.1°, directionDifferentce = 41.0°
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) targetDeltaX=5.99, targetDeltaZ=-11.03
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn Data) frontMarker="-6.4714050292969", halfVehicleWidth="2.5", directionNodeToTurnNodeLength="6.7241363525391", wpChangeDistance="3"
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn Data) reverseWPChangeDistance="5", direction="1", haveHeadlands="true", headlandHeight="15"
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn Data) numLanes="27", onLaneNum="9", turnOnField="true", reverseOffset="-5.8738098144531"
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn Data) haveWheeledImplement="true", reversingWorkTool="table: 0x01d0c1e18988", turnRadius="6.2206535339355", turnDiameter="12.441307067871"
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn Data) targetNode="92598", targetDeltaX="5.9889678955078", targetDeltaZ="-5.16064453125", zOffset="-5.8738098144531"
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn Data) reverseOffset="-5.8738098144531", isHarvester="false"
##################################################
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) Using Questionmark Turn
##################################################
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) centerOffset=-0.23168563842773, sideB=5.9889678955078, sideC=12.441307067871, centerHeight=10.904970660375
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) canTurnOnHeadland=true, headlandHeight=15.00m, spaceNeeded=14.59m
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) doNormalTurn=true, haveHeadlands=true, 8.9m < 120.0m
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) centerHeightOffset=-5.8738098144531, reverseOffset=-5.8738098144531, zOffset=-5.8738098144531, turnRadius=6.2206535339355
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) startRot=45, endRot=-73, degreeStep=9, degreeToTurn=241, clockWice=1
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) numberOfWaypoints=27, newDegreeStep=8
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 1 curentRotation=45
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 2 curentRotation=53
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 3 curentRotation=62
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 4 curentRotation=71
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 5 curentRotation=80
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 6 curentRotation=89
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 7 curentRotation=98
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 8 curentRotation=107
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 9 curentRotation=116
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 10 curentRotation=125
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 11 curentRotation=134
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 12 curentRotation=143
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 13 curentRotation=152
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 14 curentRotation=161
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 15 curentRotation=170
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 16 curentRotation=179
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 17 curentRotation=187
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 18 curentRotation=196
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 19 curentRotation=205
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 20 curentRotation=214
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 21 curentRotation=223
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 22 curentRotation=232
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 23 curentRotation=241
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 24 curentRotation=250
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 25 curentRotation=259
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 26 curentRotation=268
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 27 curentRotation=277
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) startRot=106, endRot=45, degreeStep=-9, degreeToTurn=61, clockWice=-1
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) numberOfWaypoints=8, newDegreeStep=-8
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 1 curentRotation=106
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 2 curentRotation=97
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 3 curentRotation=88
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 4 curentRotation=79
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 5 curentRotation=71
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 6 curentRotation=62
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 7 curentRotation=53
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:generateTurnCircle) waypoint 8 curentRotation=45
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=35.29, posZ=-302.25, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=34.59, posZ=-301.55, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=33.88, posZ=-300.84, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=33.17, posZ=-300.13, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=33.17, posZ=-300.13, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=33.17, posZ=-300.13, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=32.12, posZ=-299.08, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=31.08, posZ=-298.04, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=30.03, posZ=-296.99, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=28.98, posZ=-295.94, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=27.94, posZ=-294.90, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=26.89, posZ=-293.85, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=25.84, posZ=-292.80, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=24.79, posZ=-291.75, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=23.75, posZ=-290.71, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=22.70, posZ=-289.66, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=21.65, posZ=-288.61, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=20.61, posZ=-287.57, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=19.56, posZ=-286.52, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=18.51, posZ=-285.47, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=17.47, posZ=-284.43, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=16.42, posZ=-283.38, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=15.37, posZ=-282.33, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=15.37, posZ=-282.33, turnEnd=false, turnReverse=false, changeWhenPosible=true
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=37.41, posZ=-304.37, turnEnd=true, turnReverse=true, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=38.13, posZ=-305.09, turnEnd=true, turnReverse=true, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=38.85, posZ=-305.81, turnEnd=true, turnReverse=true, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn:addTurnTarget) posX=38.85, posZ=-305.81, turnEnd=true, turnReverse=true, changeWhenPosible=false
[dbg14 lp68518] AgroStar 6.61 (#1):(Turn) Generated 63 Turn Waypoints
##################################################
[dbg14 lp68518] AgroStar 6.61 (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp68540] AgroStar 6.61 (#1): curStage=0, refSpeed=10.00, curSpeed=3.68 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp70089] AgroStar 6.61 (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp70249] AgroStar 6.61 (#1): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp70249] AgroStar 6.61 (#1): setSlippingStage(..., 1)
[dbg14 lp70250] AgroStar 6.61 (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp70406] AgroStar 6.61 (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp70406] AgroStar 6.61 (#1): setSlippingStage(..., 2)
[dbg14 lp70555] AgroStar 6.61 (#1): setSlippingStage(..., 0)
[dbg14 lp80796] AgroStar 6.61 (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp80852] AgroStar 6.61 (#1): curStage=0, refSpeed=20.00, curSpeed=7.00 -> resetCustomTimer(..., "slippingStage1")

**Comment by Satissis** [comment]
Sorry, I will not have time to look into this until after the Release.

**Comment by pvajko** [comment]
Absolutely no problem Claus, could have been that you saw this problem before and knew the answer right away, definitely not a priority. Thanks.

**Comment by pvajko** [comment]
Seems to be the same as https://github.com/Courseplay/courseplay/issues/1878, closing this now.
