### ISSUE TITLE
Tractor in mod 2 not moving while browsing Shop

### ISSUE THREAD

**Issue by gec100** [pvajko/course-generator#17]
As the title says plus, but not necessary related, tractor aborts unloading and continues it's course while switching between vehicles with vehicle switcher.

the map is sudehammer if relevant

**Comment by gec100** [comment]
same thing while in the menu.

**Comment by gec100** [comment]
wrong software

**Comment by Satissis** [comment]
Yeah that's a know issue, but it's related to Vehicle Groupe Switcher.
I have talked with @DeckerMMIV about it ;)

**Comment by gec100** [comment]
thx :)
