### ISSUE TITLE
Field Edge?

### ISSUE THREAD

**Issue by sootysax** [pvajko/course-generator#2]
Can you generate courses with only the field edge?   I always record a new field edge in CP with the "reverse" mode activated to give me tighter waypoints.  Usually the generated courses have a good outer headland, but sometimes there is a crazy point jutting out, and i assume that its never quite as precise as my recorded field edge.

**Comment by pvajko** [comment]
Yes, I did that earlier with field boundaries extracted from
Courseplay and that should be way to generate courses. The current
solution which uses the outermost headland pass is just a workaround
until this generator gets integrated into Courseplay. 

I don't have
access to the game at the moment but I believe these recorded fields are
stored in an XML file as well. If that's the case, can you send me a
file then I'll check how difficult it would be to use as the input for
the generation. 

On 2017-02-27 08:23, Scott Mueller wrote: 

> Can you
generate courses with only the field edge? I always record a new field
edge in CP with the "reverse" mode activated to give me tighter
waypoints. Usually the generated courses have a good outer headland, but
sometimes there is a crazy point jutting out, and i assume that its
never quite as precise as my recorded field edge. 
> 
> --
> You are
receiving this because you are subscribed to this thread.
> Reply to
this email directly, view it on GitHub [1], or mute the thread [2].




Links:
------
[1]
https://github.com/pvajko/course-generator/issues/2
[2]

**Comment by Satissis** [comment]
Just to shed some light on saving the field edges.
By default none is saved, but rescanned each time you start the game or buy a new field.

You can save them thou.
What you would have to do, is drive inside the field, and then without any course loaded, there should be an calculate field edges in the main page and once that's done, you can save it to a slot number, which is normal the field number if you use the auto scan.
Once it's saved and save the game, there is an `courseplayCustomFields.xml` file inside your savegame folder for that save and it contains those fields you have scanned and saved your self.

I believe you can also save an recorded course as field edges. ( Can't remember 100% thou)

**Comment by pvajko** [comment]
@sootysax @Satissis Thanks, that seems to work fine. I started the branch https://github.com/pvajko/course-generator/tree/loadFields to read field data from courseplayCustomFields.xml.

**Comment by pvajko** [comment]
https://github.com/pvajko/course-generator/releases/tag/v0.2 (20816126b3cc61611dd3e97ffd5f4106b8750ce4) has now the ability to load saved fields.

**Comment by pvajko** [comment]
Can we close this?

**Comment by krambc** [comment]
I can generate a course from a fieldwork course, but not from a saved field. 
![sin titulo](https://cloud.githubusercontent.com/assets/25364738/23622079/7c2d198c-029d-11e7-97f5-4b0498a5cc01.png)
I've tried to load a field by typing in the number of the field but doesn't work. Maybe i'm doing something wrong, but i've followed your readme step by step.

**Comment by pvajko** [comment]
You don't seem to have any saved fields. Follow @Satissis description earlier in this discussion to save a field then you should see a list of the saved fields above the 'Enter number...' prompt.

**Comment by krambc** [comment]
I've done this way. I'll try later again

**Comment by pvajko** [comment]
Please check if you have a file named courseplayCustomFields.xml under your savegame1 folder. If the file is there and you don't see a list of fields, please post the file here.

**Comment by krambc** [comment]
Well, i've tried again. I've noticed that the CustomFields.xml doesn't updat till you exit the game. I've checked after saving the field and ther was nothing in the file. After leaving the game ther is.
![imagen](https://cloud.githubusercontent.com/assets/25364738/23630287/ddba2434-02ba-11e7-8f42-ad67a6dd6aa8.png)

I've tried again and have a new issue.
![sin titulo](https://cloud.githubusercontent.com/assets/25364738/23630309/efeca6c2-02ba-11e7-8a98-85217ae8eafb.png)

Sure i'm doing something wrong. I'm dumb and I need a youtube tutorial tu restar my laptop :-)

On the other hand, i've noticed that if i've the courseplay courses organized in folders ingame, the script doesn't work. Is this correct or i'm doing something wrong again?

Thank you very much for your effort in this project and apologize for my clumsiness. I hope I can learn and collaborate by testing the course generator.

P.S. apologize for my english. Isn's as good as i wish.
https://github.com/login?return_to=%2FCourseplay%2Fcourseplay

**Comment by pvajko** [comment]
The error message in the screenshot above, is that for a map where you have your Courseplay courses in folders? Can you post your courseManager.xml from the Map01 folder?

(Please note that as this generator is an interim solution only, I did not plan supporting subfolders (as the README also states). However, courses in the top folder should show up.

**Comment by krambc** [comment]
Yes it is. I've all the courses organized in folders except the ones i've created for coursegenerator. I post my courseManager.xml later

**Comment by krambc** [comment]
Hi. I've tried again just in case i've done something wrong yesterday and i get the same result.
![imagen](https://cloud.githubusercontent.com/assets/25364738/23670907/9bf8d72a-0369-11e7-996d-f52a2922e908.png)
I have 3 courses in the top folder: C14 gen and C12-gen (that i create for use course generator) and the one called C15/barn bales (that i forget to organize into a folder)

**Comment by pvajko** [comment]
Thanks, opened a separate issue #10 for the subfolder problem to be able to close this one.
