### ISSUE TITLE
Course Generator integrated with Courseplay

### ISSUE THREAD

**Issue by pvajko** [pvajko/course-generator#22]
I made a first usable version with the new generator integrated at https://github.com/pvajko/courseplay, see the last commit:

![auto](https://user-images.githubusercontent.com/2379521/27015411-d4162a2c-4ed2-11e7-80d9-7e6ed443a1b4.PNG)

Updated HUD and hooked up settings

You can now select 'Vehicle location' in the HUD as
starting corner. If you do so, Starting Direction is set to
automatic too and one headland is selected (can't yet generate
without headland)

Also, hooked up the number of headlands, clockwise/counterclockwise
and headland/center order to the new generator.

If you select anything other than 'Vehicle location' for the
starting corner, the old generator is invoked.

**Comment by gec100** [comment]
i'm getting this error:
`## Courseplay: setting up hud
Error: Running LUA method 'loadMapFinished'.
mods/zzz_courseplay/hud.lua:96: table index is nil`

tested on Sosnovka and Thorthon farm

**Comment by pvajko** [comment]
How did you install it? I suspect it's a problem with the git submodule, but I may be wrong.

I did not realize that Github is not so great with submodules and when you download a ZIP from the repository it does not include the submodule. That may be a problem. 

If you are familiar with git, you can clone https://github.com/pvajko/courseplay, change into the directory and run `git submodule init`
`git submodule update`
which will pull in the course-generator code.
 
Alternatively, you can download https://github.com/pvajko/courseplay and then https://github.com/pvajko/course-generator into mods/courseplay.

I guess the best what I can do is to provide a courseplay release here, will do it in the next days.

**Comment by pvajko** [comment]
Try this: https://github.com/pvajko/course-generator/releases/download/v1.0-with-coursplay/courseplay-with-course-generator-v1.0.zip

**Comment by JDTiger** [comment]
used it, get: 
`Error: Running LUA method 'mouseEvent'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/generateCourse.lua:80: attempt to call global 'generate' (a nil value)`
on field 40 of Lossberg map from Modhub

**Comment by pvajko** [comment]
How did you install it? Looks like you have the course-generator folder under zzz_Courseplay but it is empty. This happens when you clone from https://github.com/pvajko/courseplay but don't run `git submodule update --init` afterwards in the courseplay folder.

But if you download and extract https://github.com/pvajko/course-generator/releases/download/v1.0-with-coursplay/courseplay-with-course-generator-v1.0.zip, you should be fine, I just tried it and generated Field 40 for Lossberg.

**Comment by JDTiger** [comment]
well i did that before, redownloaded, put it in the courseplay.zip and get the same error...
![screenhunter_34 jun 14 15 00](https://user-images.githubusercontent.com/9157835/27133484-86f563d8-5112-11e7-9acf-3366a3741f0c.jpg)

**Comment by pvajko** [comment]
Not sure what 'put it in the courseplay.zip' exactly means. 

If you want try this: remove that zzz_Courseplay completely from you mods folder and extract https://github.com/pvajko/course-generator/releases/download/v1.0-with-coursplay/courseplay-with-course-generator-v1.0.zip in the mods folder. That should create a courseplay folder (containing the Courseplay **and** the course-generator within.

**Comment by gec100** [comment]
it is a mod issue. with only CP loaded it works. Must check what mod is making problems

**Comment by pvajko** [comment]
Thanks, that's great info. Must be something with the order of the mods loading and the way files are sourced in Lua. 
I'll try to reproduce it by renaming to zzz_courseplay so it loads last. In the meanwhile, if you could post your full logfile that would probably help.

Thank you for helping out.

**Comment by gec100** [comment]
sure. here it is. did not check if the error is still in the log cause i've run the game with CP unzipped and there is no probs.

**Comment by gec100** [comment]
[log.zip](https://github.com/pvajko/course-generator/files/1075502/log.zip)

**Comment by gec100** [comment]
nope the log is overwritten. I'll reproduce it

**Comment by pvajko** [comment]
yeah. I see this worked.

**Comment by gec100** [comment]
now i got it :) 
[log.zip](https://github.com/pvajko/course-generator/files/1075521/log.zip)

**Comment by pvajko** [comment]
Ok. I see what the problem is but don't know at the moment how to fix it. Looks like it does not work when the mod is zipped. Do you have it zipped?

You should be able to work around it by unzipping the contents in a folder under mods so it looks like this:

![folder](https://user-images.githubusercontent.com/2379521/27149429-2405c334-5109-11e7-8f24-13ae06ca5381.PNG)

**Comment by gec100** [comment]
yes. no problems when it's unzipped

**Comment by JDTiger** [comment]
ok, will try with folder... thought it was to be installed like a CP-Update (i download the new zip from the github-Page, empty the old zzz_Coursplay.zip and put all files in it...)

**Comment by pvajko** [comment]
Glad it works.

Sorry guys, I'll try to make the zipped versions work when I get home...

**Comment by debejerry** [comment]
Hi, first things first: great work!!
I've got it running, one error caught me.
I've got “ generateCourse.lua:80: attempt to call global 'generate' (a nil value)“.
The course was already generated and I clicked “Start at forst waypoint“, I then stopped CP and drove near the first way point and told CP to “Start at the nearest waypoint“ that worked and no error recorded.
I don't know if mine and gec100's errors are related, but I hope I could help a bit.

**Comment by pvajko** [comment]
Thanks for testing! Could you post your log.txt?

**Comment by pvajko** [comment]
Ok, I think I have a fix now at https://github.com/pvajko/course-generator/releases/download/v1.0-with-courseplay/ZZZ_courseplay.zip

I'd really appreciate if one of you could try it, just download it and drop it in the mods folder, no extraction needed. Remove any other courseplay zips or folders before.

Thanks

**Comment by gec100** [comment]
first tests show no problems.

not sure how complicated that would be but is it possible to take in the account the turn radius of the vehicle (when it's grater than pre-calculated one) when calculating corners?

**Comment by pvajko** [comment]
Thanks for testing.

The turning radius is in the works already on this branch: https://github.com/pvajko/course-generator/tree/radius and has its own issue #13. Taking it over from CP is not the problem, but let's discuss it there.

The version integrated with Courseplay does not have all the tweaking possibilities of the standalone version, but I'm planning to add some of those I'm just not sure which ones are actually useful for the folks here. What would you think would make sense to add to the integrated version:
1. headland overlap (I had good results with 10% overlapping headlands to eliminate missing crop in the corners)
2. select headland start location on map
3. skipping tracks pattern

**Comment by gec100** [comment]
my 2 cc
1. 10% overlap is good
2. headland start from vehicle position is also good 
3. skipping track although good idea at start, in practice not so good if you plan to use more than one machine on one field in one time.

like i said... just my 2 cc

**Comment by pvajko** [comment]
@gec100 thanks for the input, it is very valuable. 
One question: would anyone be interested in manually setting the angle of the up/down tracks in the center (instead of automatically choosing the optimal angle)?

**Comment by krambc** [comment]
I've donloaded the file. i've copied to mod folders and nothing. The CP HUD appears as usual, no changes, no posibiliti of choice de vehicle position....

**Comment by pvajko** [comment]
@krambc , The integrated version has its own issue tracking, I moved this over there:
https://github.com/pvajko/courseplay/issues/4

**Comment by gec100** [comment]
course generator is enabled when u select _**vehicle location**_ in **_starting corner_** and course start is calculated from current vehicle position.

**Comment by krambc** [comment]
I apologize. It works perfectly. I haven't cheked the starting corner. I am embaraced.

**Comment by pvajko** [comment]
This course generator has now been integrated into the official Courseplay repository.
