### ISSUE TITLE
Error file.lua:90: attempt to call global 'calculatePolygonData' (a nil value)

### ISSUE THREAD

**Issue by JDTiger** [pvajko/course-generator#28]
Tried using the Coursegenerator froim the newest CP/headlands tree, may have done something wrong ion trying to get it working...

I downloaded the Coursegenerator V1.0 release and replaced all files with the one from the headlands tree... resulting in the error you see in the title

**Comment by pvajko** [comment]
Did not think anyone else other than me would use this. I'm not maintaining the startCourseGenerator script, I use this almost exclusively from the IntelliJ Idea IDE.

I changed this that the course-generator has the courseplay embedded (easier to work with git) so you'd have to clone this pvajko/course-generator master branch and then in the folder where you cloned it to, clone Courseplay/courseplay (in this case the headlands branch) so there'll be a course-generator/courseplay folder.  And then you can run LOVE\love.exe . fromFile fields/Goldcrest.xml 12 for example.
