### ISSUE TITLE
Turning off combine/implements when moving between headland and center tracks

### ISSUE THREAD

**Issue by pvajko** [pvajko/course-generator#3]
When tracks can have any direction and the headland tracks may start anywhere, there will inevitably be a segment where the vehicle must move from the last waypoint of the headland track to the first waypoint of the parallel tracks in the center of the field (or the other way round). 

See the segment highlighted in red in the screenshot:

![capture](https://cloud.githubusercontent.com/assets/2379521/23374451/f9b412ac-fce9-11e6-89cf-d5fa6434adfe.PNG)

What needs to be in the course XML file so the vehicle is not harvesting/sowing/working the field while it is on that segment? Looking for XML tags to turn off/on a combine or implement. Maybe @Satissis has an idea?

**Comment by Satissis** [comment]
as of right now, there is no real safe way to do that until I start on the new Turn Maneuver Part 2, which is for headlands. Then we can add an marker in the generated course to tell it to make an specific turn that drives from one point to another and then start again.

**Comment by pvajko** [comment]
Implemented in courseplay.
