### ISSUE TITLE
does not see the harvester

### ISSUE THREAD

**Issue by GektorA** [pvajko/course-generator#36]
Hello! Sorry, I don't speak English.
I have been using CoursePlay. Installed new <version>6.03.00052</version>. Problems started.
I will explain in the picture https://drive.google.com/file/d/1viCG86zNgkD7_yi6Nz5n7tuLrPBLIrJh/view?usp=sharing
Can you fix it?
Thanks in advance!

**Comment by pvaiko** [comment]
@GektorA, please report issues with Coursepaly here: https://github.com/Courseplay/courseplay/issues
