### ISSUE TITLE
cant'open fieldwork course

### ISSUE THREAD

**Issue by debejerry** [pvajko/course-generator#4]
First things first: Great work, really appreciate it!! :+1: 

as @gec100 commented on courseplay issue 1793.
I have the very same problem.

I've setup coursegen as you wrote, if I try to load i.e. the Fichtelberg course you delivered within the package everything works as you described.
As soon as I try to load a fieldwork generated course I saved within courseplay  on "Gemeinde Rade" map coursegen gets stuck at the prompt and doesn't load further.
Only chance to get the cursor back is Ctrl-C or entering 0 (Zero)

Maybe you have any advice what I'm doing wrong while generating my course :crying_cat_face:  :smile:

**Comment by gec100** [comment]
one thing i've noted.

![cmd](https://cloud.githubusercontent.com/assets/8178773/23375088/53167280-fd27-11e6-811e-d17e5e960489.JPG)

you can see that in first attempt i was trying to open course with number 6 in front of it. but that did not work. than i noticed that it saiz "Enter number ( **1 - 4** ) for the selected ..."

After selecting number 4 being forth line in the list, that worked. 

so basically coursegen mixes up the course numbers with line numbers

**Comment by debejerry** [comment]
I think I found it.

It seems to be that there are two causes that lead coursegen to get stuck:

1. If the courses are not saved in order (by ID  and/or filename)  coursegen detects and displays the courses as options to select but if you type in an id and hit enter it gets stuck.
As coursplay does use the save slots IDs and filenames will get out of order which should not (but does for coursegen obviously) hurt as the IDs are used as identifiers.

2. Courseplay seems to not always store the single attributes of course in the same order within the xml file. This also seems to confuse coursegen.

Example, my courseManager.xml that did not work:

> <courseManager>
    <saveSlot>
        <slot fileName="courseStorage0001.xml" id="1" parent="0" isUsed="true" name="F29/Hof N"/>
        <slot fileName="courseStorage0002.xml" id="2" parent="0" isUsed="true" name="F27/Hof N"/>
        <slot fileName="courseStorage0003.xml" id="3" parent="0" isUsed="true" name="Shop/Hof N"/>
        <slot fileName="courseStorage0004.xml" isUsed="true" id="4" parent="0" name="Hof N/F27"/>
        <slot fileName="courseStorage0005.xml" isUsed="true" id="16" parent="0" name="FR Wiese am Hof"/>
        <slot fileName="courseStorage0006.xml" isUsed="true" id="15" parent="0" name="Rade O/Hof N"/>
        <slot fileName="courseStorage0007.xml" isUsed="true" id="11" parent="0" name="Getreide AG/F27"/>
        <slot fileName="courseStorage0008.xml" id="8" parent="0" isUsed="true" name="Getreide AG/KR F8/5"/>
        <slot fileName="courseStorage0009.xml" isUsed="true" id="9" parent="0" name="KR F8/5 Rade Ost Teil1"/>
        <slot fileName="courseStorage0010.xml" isUsed="true" id="14" parent="0" name="Hof N/F29"/>
        <slot fileName="courseStorage0011.xml" id="12" parent="0" isUsed="true" name="Getreide AG/Rade O"/>
        <slot fileName="courseStorage0012.xml" id="13" parent="0" isUsed="true" name="F27/Getreide AG"/>
        <slot fileName="courseStorage0013.xml" id="17" parent="0" isUsed="true" name="NO_S_4M_F108"/>
    </saveSlot>
</courseManager>

My corrected courseManager.xml that works:

> <courseManager>
    <saveSlot>
        <slot fileName="courseStorage0001.xml" id="1" parent="0" isUsed="true" name="F29/Hof N"/>
        <slot fileName="courseStorage0002.xml" id="2" parent="0" isUsed="true" name="F27/Hof N"/>
        <slot fileName="courseStorage0003.xml" id="3" parent="0" isUsed="true" name="Shop/Hof N"/>
        <slot fileName="courseStorage0004.xml" id="4" parent="0" isUsed="true" name="Hof N/F27"/>        
		<slot fileName="courseStorage0005.xml" id="5" parent="0" isUsed="true" name="Getreide AG/KR F8/5"/>
        <slot fileName="courseStorage0006.xml" id="6" parent="0" isUsed="true" name="KR F8/5 Rade Ost Teil1"/>        
        <slot fileName="courseStorage0007.xml" id="7" parent="0" isUsed="true" name="Getreide AG/F27"/>
        <slot fileName="courseStorage0008.xml" id="8" parent="0" isUsed="true" name="Getreide AG/Rade O"/>
        <slot fileName="courseStorage0009.xml" id="9" parent="0" isUsed="true" name="F27/Getreide AG"/>
        <slot fileName="courseStorage0010.xml" id="10" parent="0" isUsed="true"name="Hof N/F29"/>
        <slot fileName="courseStorage0011.xml" id="11" parent="0" isUsed="true"name="Rade O/Hof N"/>
         <slot fileName="courseStorage0012.xml" id="12" parent="0" isUsed="true" name="FR Wiese am Hof"/>
         <slot fileName="courseStorage0013.xml" id="13" parent="0" isUsed="true" name="NO_S_4M_F108"/>
    </saveSlot>
</courseManager>

**Comment by pvajko** [comment]
Great troubleshooting, thanks!
I'll fix it.

**Comment by pvajko** [comment]
@debejerry @gec100 thanks for troubleshooting, I uploaded a fix to http://vajko.name/coursegen.zip

If you are familiar with git you can also pull it from github.
