### ISSUE TITLE
Can't start script

### ISSUE THREAD

**Issue by JDTiger** [pvajko/course-generator#7]
hey,
maybe its because i'm dumb, maybe because its late, or maybe its just that i misinterpreted the Readme...
I can't get the script to run, I type the command in cmd.exe, but the only result i get is the following error:
'lua.exe' is not recognized as an internal or external command,
operable program or batch file.

Hopefully someone can explain what i did wrong...
Greets JD_Tiger

PS: i attached a picture of my coursefolder, the unziped script and the cmd window...
![screenhunter_23 mar 05 00 30](https://cloud.githubusercontent.com/assets/9157835/23583118/7d3640e6-013b-11e7-9d28-72f1c1002276.jpg)

**Comment by pvajko** [comment]
Nothing is wrong with you, I'm an idiot, replaced the lua script in the release but did not update the readme. 
Use lua53.exe instead of lua.
Sorry

**Comment by JDTiger** [comment]
Well, the only difference i see with the new code, is that the error changed to 
`C:\Users\nitro\Desktop\FS17-CourseGen>lua53.exe startCourseGenerator.lua "C:\Users\nitro\Documents\My Games\FarmingSimulator2017\CoursePlay_Courses\FS17_dutchPolder.SampleModMap"
'lua53.exe' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by pvajko** [comment]
Are you using the unzipped release at https://github.com/pvajko/course-generator/files/815691/course-generator.zip?
That has the lua53.exe bundled. If you downloaded or cloned the source, you must have lua and LOVE from love2d.org installed.

**Comment by JDTiger** [comment]
Aah... That explains it... Yep i used the source... Thought everything was included in the main github...

**Comment by JDTiger** [comment]
Ok, now it works, thanks :D
