### ISSUE TITLE
Overlapping a few headlands?

### ISSUE THREAD

**Issue by manierim** [pvajko/course-generator#9]
Great work here!
Do you think it could be possible to have the internal lanes "overlapping" a given number of inner headlands?
That would be very useful for those big ploughs!

**Comment by pvajko** [comment]
If you mean that the tracks in the center of the field should not end at the innermost headland track but at one of the outer headland tracks, then yes, that should not be a problem. What exactly is the benefit of that?

**Comment by manierim** [comment]
That is exactly what I mean.
This is mainly useful with long "diagonal" ploughs.
They usually leave a rather big "V" at the end of each lane, either with CP or with the standard helper.
I usually override this running a normal CP generated course with none or one headland (after the inner lanes).
Then I generate a second course with 2 or more headlands before and then stop  CP manually when these are done.

**Comment by pvajko** [comment]
Ok, got it. 
The easiest way to implement this would be to define how far in meters should the tracks go beyond the innermost headland. Currently they stop at half the implement width, but that could be a parameter you can tweak.

**Comment by manierim** [comment]
The issue for which this would be helpful has just been posted as a CP issue:
https://github.com/Courseplay/courseplay/issues/1864

**Comment by pvajko** [comment]
Pushed a solution to this on branch issue_9, would be great if you could give it a try before I build a release.

**Comment by manierim** [comment]
Tested, works exactly as expected! Very good Job.
I look forward to see all your excellent work available directly inside CP!!!
